---
title: "About"
---

My name is Alan Tao, and this website is a project I made in [Kane's Free Data Science Bootcamp](https://bootcamp.davidkane.info/){target="blank"}. I'm really interested in music in general, so I decided to focus my project on this topic. Making this website took a lot of effort because Bayesian regression models take a long time to run. Please support me by viewing my work and also my [YouTube Channel](https://www.youtube.com/channel/UCzdtyvYuUM6EGKhtsbF_jhQ){target="blank"}. 

## Why is it called v2?
This is a deeper analysis of spotify songs using the [30000 Spotify Songs](https://www.kaggle.com/datasets/joebeachcapital/30000-spotify-songs){target="blank"} dataset. This is an extension to the exploratory analysis of Spotify songs: [Spotify Songs v1](https://alienjao.quarto.pub/spotify-songs/pages/index.html){target="blank"}. These two projects are both created in [Kane's Free Data Science Bootcamp](https://bootcamp.davidkane.info/){target="blank"}.

## What is a standard deviation?
Standard deviation is a measure for the spread of data. Standard deviation is measured with the following steps:

1. Take the difference between each value from the data and the mean of the data
2. Square those numbers
3. Take the average of the squared numbers
4. Take the square root of the average

A cool fact is that 2 standard deviations above and below the mean roughly covers around 95% of the dataset. 

## Contact
Email: alantaolr@outlook.com\
Website: [alantao.com](https://alantao.com){target="blank"}\
GitHub: [https://github.com/alantao5056](https://github.com/alantao5056){target="blank"}\
YouTube: [https://www.youtube.com/channel/UCzdtyvYuUM6EGKhtsbF_jhQ](https://www.youtube.com/channel/UCzdtyvYuUM6EGKhtsbF_jhQ){target="blank"}
